openapi: 3.0.0
info:
  title: Auth Service API
  version: 1.0.0
  description: API for user authentication and authorization in CodeAssess
servers:
  - url: http://localhost:3001/api/auth
    description: Local Auth Service
  - url: http://localhost:3000/api-gateway/auth
    description: API Gateway
paths:
  /register:
    post:
      summary: Register a new user
      tags: [Authentication]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password, firstName, lastName, role]
              properties:
                email: { type: string, format: email }
                password: { type: string, format: password }
                firstName: { type: string }
                lastName: { type: string }
                role:
                  {
                    type: string,
                    enum: [candidate, recruiter, hiring-manager, admin],
                  }
      responses:
        201:
          description: User registered successfully
  /login:
    post:
      summary: Login user
      tags: [Authentication]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email: { type: string, format: email }
                password: { type: string }
      responses:
        200:
          description: Login successful
  /refresh-token:
    post:
      summary: Refresh authentication token
      tags: [Authentication]
      responses:
        200:
          description: Token refreshed
  /logout:
    post:
      summary: Logout user
      tags: [Authentication]
      responses:
        200:
          description: Logged out
  /me:
    get:
      summary: Get current user profile
      tags: [Authentication]
      security:
        - bearerAuth: []
      responses:
        200:
          description: User profile data
  /verify:
    post:
      summary: Internal token verification
      tags: [Internal]
      responses:
        200:
          description: Token is valid
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
