openapi: 3.0.0
info:
  title: Job Service API
  version: 1.0.0
  description: API for managing jobs and applications in CodeAssess
servers:
  - url: http://localhost:3002/api
    description: Local Job Service
  - url: http://localhost:3000/api-gateway/jobs
    description: API Gateway
paths:
  /jobs/public:
    get:
      summary: Get all public jobs
      tags: [Jobs]
      responses:
        200:
          description: List of jobs
  /jobs/public/{link}:
    get:
      summary: Get public job by link
      tags: [Jobs]
      parameters:
        - name: link
          in: path
          required: true
          schema: { type: string }
      responses:
        200:
          description: Job details
  /jobs:
    get:
      summary: Get all jobs (protected)
      tags: [Jobs]
      security:
        - bearerAuth: []
      responses:
        200:
          description: List of jobs
    post:
      summary: Create a new job
      tags: [Jobs]
      security:
        - bearerAuth: []
      responses:
        201:
          description: Job created
  /jobs/{id}:
    get:
      summary: Get job by ID
      tags: [Jobs]
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: string }
      responses:
        200:
          description: Job details
  /applications/apply:
    post:
      summary: Apply for a job
      tags: [Applications]
      security:
        - bearerAuth: []
      responses:
        201:
          description: Application submitted
  /applications/my-applications:
    get:
      summary: Get my job applications
      tags: [Applications]
      security:
        - bearerAuth: []
      responses:
        200:
          description: List of applications
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Job:
      type: object
      properties:
        id: { type: string }
        title: { type: string }
        description: { type: string }
        location: { type: string }
        status:
          {
            type: string,
            enum:
              [
                draft,
                pending_approval,
                approved,
                published,
                closed,
                filled,
                cancelled,
              ],
          }
